# Generated by Django 4.1.1 on 2022-11-02 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transaction')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('pickup_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transaction')),
                ('shipping_order_id', models.ForeignKey(on_delete=models.SET('N/A'), related_name='items', to='order_management.shippingorder')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=128)),
                ('package_type', models.CharField(choices=[('PL', 'Pallet'), ('BX', 'Box'), ('BU', 'Bulk')], max_length=2)),
                ('weight_unit', models.CharField(choices=[('LB', 'POUNDS'), ('KG', 'KILOGRAMS'), ('OZ', 'OUNCE')], max_length=2)),
                ('dimension_unit', models.CharField(choices=[('IN', 'INCHES'), ('FT', 'FEET'), ('YD', 'YARD'), ('MT', 'METER'), ('CM', 'CENTIMETER')], max_length=2)),
                ('purchase_order_id', models.ForeignKey(on_delete=models.SET('N/A'), related_name='items', to='order_management.purchaseorder')),
            ],
        ),
    ]
