# Generated by Django 4.1.4 on 2022-12-28 15:03

from django.db import migrations, models
import django.db.models.deletion
import modules.order_management.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_transaction_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transaction')),
                ('mode', models.CharField(choices=[('TL', 'Truck Load'), ('LTL', 'Less than Truck Load'), ('PTL', 'Partial Truck Load'), ('RAIL', 'Rail'), ('DRAYAGE', 'Drayage')], default=None, max_length=7, null=True)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('pickup_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('reference', models.CharField(default='', max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transaction')),
                ('shipping_order_id', models.ForeignKey(on_delete=models.SET('N/A'), to='order_management.shippingorder')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=128)),
                ('count', models.CharField(default=0, max_length=7, validators=[modules.order_management.utils.Validators.zero_not_first_integer])),
                ('package_type', models.CharField(choices=[('PL', 'Pallet'), ('BX', 'Box'), ('BU', 'Bulk')], max_length=2)),
                ('weight', models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.validate_comma_separated_integer])),
                ('weight_unit', models.CharField(choices=[('LB', 'POUNDS'), ('KG', 'KILOGRAMS'), ('OZ', 'OUNCE')], max_length=2)),
                ('height', models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer])),
                ('width', models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer])),
                ('length', models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer])),
                ('dimension_unit', models.CharField(choices=[('IN', 'INCHES'), ('FT', 'FEET'), ('YD', 'YARD'), ('MT', 'METER'), ('CM', 'CENTIMETER')], max_length=2)),
                ('purchase_order_id', models.ForeignKey(on_delete=models.SET('N/A'), related_name='items', to='order_management.purchaseorder')),
            ],
        ),
    ]
