# Generated by Django 4.1.4 on 2022-12-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item'),
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.item')),
                ('purchase_order_id', models.ForeignKey(on_delete=models.SET('N/A'), related_name='items', to='order_management.purchaseorder')),
            ],
            bases=('core.item',),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
