# Generated by Django 4.1.4 on 2022-12-28 14:58

from django.db import migrations, models
import modules.order_management.utils


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.CharField(default=0, max_length=7, validators=[modules.order_management.utils.Validators.zero_not_first_integer]),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer]),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer]),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.validate_comma_separated_integer]),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer]),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='mode',
            field=models.CharField(choices=[('TL', 'Truck Load'), ('LTL', 'Less than Truck Load'), ('PTL', 'Partial Truck Load'), ('RAIL', 'Rail'), ('DRAYAGE', 'Drayage')], default=None, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='reference',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_order_id',
            field=models.ForeignKey(on_delete=models.SET('N/A'), to='order_management.shippingorder'),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
    ]
