# Generated by Django 4.1.4 on 2022-12-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_iteminstance_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='special_instructions',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
