# Generated by Django 4.1.4 on 2022-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_iteminstance_special_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='special_instructions',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
