# Generated by Django 4.1.4 on 2022-12-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_alter_iteminstance_special_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='serial_number',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
