# Generated by Django 3.2.2 on 2023-01-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230119_1809'),
        ('order_management', '0005_iteminstance_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='core.organization'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='core.organization'),
        ),
    ]
