# Generated by Django 3.2.2 on 2023-01-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230119_1809'),
        ('order_management', '0006_auto_20230123_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='carrier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier', to='core.organization'),
        ),
        migrations.CreateModel(
            name='FacilityStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('STORAGE', 'Storage'), ('CORPORATE', 'Corporate Office'), ('WAREHOUSE', 'Warehouse'), ('FACILITY', 'Facility')], default='WAREHOUSE', max_length=10)),
                ('facility', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='core.facility')),
            ],
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='ship_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='order_management.facilitystop'),
        ),
    ]
