# Generated by Django 3.2.2 on 2023-01-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230119_1809'),
        ('order_management', '0008_auto_20230123_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='facility_type',
            field=models.CharField(choices=[('STORAGE', 'Storage'), ('CORPORATE', 'Corporate Office'), ('WAREHOUSE', 'Warehouse'), ('FACILITY', 'Facility')], default='WAREHOUSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='ship_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='ship_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.facility'),
        ),
        migrations.DeleteModel(
            name='FacilityStop',
        ),
    ]
