# Generated by Django 3.2.19 on 2023-07-31 21:55

from django.db import migrations, models
import django.db.models.deletion
import modules.core.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(default=None, max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(default=None, max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(default=None, max_length=40, verbose_name='Email')),
                ('phone', models.CharField(default=None, max_length=20, verbose_name='Phone')),
                ('observations', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('working_days', models.JSONField(default=modules.core.utils.default_days_week)),
                ('working_hour_start', models.TimeField(blank=True, default=None, null=True)),
                ('working_hour_end', models.TimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('zip_code', models.CharField(default=None, max_length=10, null=True)),
                ('street', models.CharField(default=None, max_length=50, null=True)),
                ('street_number', models.IntegerField(default=0)),
                ('city', models.CharField(default=None, max_length=20, null=True)),
                ('state', models.CharField(default=None, max_length=20, null=True)),
                ('country', models.CharField(choices=[('UNITED STATES', 'United states'), ('BRAZIL', 'Brazil'), ('ARGENTINA', 'Argentina'), ('CANADA', 'Canada'), ('MEXICO', 'Mexico'), ('GREAT BRITAIN', 'Great britain'), ('URUGUAY', 'Uruguay')], max_length=20)),
                ('observations', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('refrigerated_storage', models.BooleanField(default=False)),
                ('drop_trailer', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contact')),
                ('dispatch_contact', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contact')),
            ],
            options={
                'verbose_name_plural': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('part_number', models.CharField(default=None, max_length=50, null=True)),
                ('commodity', models.CharField(max_length=128)),
                ('count', models.IntegerField(default=0, validators=[modules.core.utils.Validators.zero_not_first_integer])),
                ('package_type', models.CharField(choices=[('PL', 'Pallet'), ('BX', 'Box'), ('BU', 'Bulk')], max_length=2)),
                ('weight_package_unit', models.CharField(choices=[('LB', 'POUNDS'), ('KG', 'KILOGRAMS'), ('OZ', 'OUNCE')], max_length=2)),
                ('weight', models.CharField(max_length=3)),
                ('height_package_unit', models.IntegerField(default=0, validators=[modules.core.utils.Validators.zero_not_first_integer])),
                ('width_package_unit', models.IntegerField(default=0, validators=[modules.core.utils.Validators.zero_not_first_integer])),
                ('length_package_unit', models.IntegerField(default=0, validators=[modules.core.utils.Validators.zero_not_first_integer])),
                ('dimension_unit', models.CharField(choices=[('IN', 'INCHES'), ('FT', 'FEET'), ('YD', 'YARD'), ('MT', 'METER'), ('CM', 'CENTIMETER')], max_length=2)),
                ('hazardous', models.BooleanField(default=False)),
                ('temperature_controlled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('kind', models.CharField(blank=True, choices=[('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('SHIPPER', 'Shipper'), ('CONSIGNEE', 'Consignee'), ('CARRIER', 'Carrier'), ('TRANSPORT_MANAGER', 'Transport_manager'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=1024, verbose_name='Kind')),
                ('yearly_revenue', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporateOffice',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.facility')),
                ('billable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Corporate Office',
                'verbose_name_plural': 'Corporate Offices',
            },
            bases=('core.facility',),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.facility')),
                ('free_reschedule_enabled', models.BooleanField(default=True)),
                ('allow_repackaging_until_appointment', models.BooleanField(default=True)),
                ('time_allowed_for_repackaging_before_appointment', models.TimeField(blank=True, default=None, null=True)),
                ('detention_daily_cost', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.facility',),
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrigerated_cargo', models.BooleanField(default=False)),
                ('drop_trailer', models.BooleanField(default=False)),
                ('drayage_enabled', models.BooleanField(default=False)),
                ('live_load', models.BooleanField(default=True)),
                ('hazmat', models.BooleanField(default=False)),
                ('dock_dispatch_contact', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contact')),
                ('warehouse', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Warehouse', to='core.warehouse')),
            ],
        ),
    ]
