# Generated by Django 3.2.19 on 2023-07-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facility_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='dock',
            name='appointment_slot_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dock',
            name='dock_label',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_label',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
