# Generated by Django 4.1.4 on 2022-12-28 16:33

from django.db import migrations, models
import modules.order_management.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=128)),
                ('count', models.CharField(default=0, max_length=7, validators=[modules.order_management.utils.Validators.zero_not_first_integer])),
                ('package_type', models.CharField(choices=[('PL', 'Pallet'), ('BX', 'Box'), ('BU', 'Bulk')], max_length=2)),
                ('weight_package_unit', models.CharField(choices=[('LB', 'POUNDS'), ('KG', 'KILOGRAMS'), ('OZ', 'OUNCE')], max_length=2)),
                ('height_package_unit', models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer])),
                ('width_package_unit', models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer])),
                ('length_package_unit', models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer])),
                ('dimension_unit', models.CharField(choices=[('IN', 'INCHES'), ('FT', 'FEET'), ('YD', 'YARD'), ('MT', 'METER'), ('CM', 'CENTIMETER')], max_length=2)),
            ],
        ),
    ]
