# Generated by Django 4.1.4 on 2022-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hazardous',
            field=models.BooleanField(default=False),
        ),
    ]
