# Generated by Django 3.2.19 on 2023-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230731_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dock',
            old_name='appointment_slot_time',
            new_name='appointment_slot_time_hours',
        ),
        migrations.AddField(
            model_name='dock',
            name='lumper_required',
            field=models.BooleanField(default=False),
        ),
    ]
