# Generated by Django 4.1.4 on 2023-01-03 16:55

from django.db import migrations, models
import modules.order_management.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_part_number_item_temperature_controlled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=0, validators=[modules.order_management.utils.Validators.zero_not_first_integer]),
        ),
    ]
