# Generated by Django 3.2.2 on 2023-01-10 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230110_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='external_contact_name',
            field=models.CharField(default=None, max_length=120, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='internal_contact_name',
            field=models.CharField(default=None, max_length=120, verbose_name='Account Manager'),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('zip_code', models.CharField(default=None, max_length=10, null=True)),
                ('street', models.CharField(default=None, max_length=50, null=True)),
                ('street_number', models.IntegerField(default=0)),
                ('city', models.CharField(default=None, max_length=20, null=True)),
                ('state', models.CharField(default=None, max_length=20, null=True)),
                ('country', models.CharField(choices=[('UNITED STATES', 'Usa'), ('BRAZIL', 'Bra'), ('ARGENTINA', 'Arg'), ('CANADA', 'Can'), ('MEXICO', 'Mex'), ('GREAT BRITAIN', 'Gbr'), ('URUGUAY', 'Uru')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
