# Generated by Django 3.2.2 on 2023-01-11 16:34

from django.db import migrations, models
import django.db.models.deletion
import modules.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230110_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.facility')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.facility',),
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.AlterField(
            model_name='facility',
            name='country',
            field=models.CharField(choices=[('UNITED STATES', 'United states'), ('BRAZIL', 'Brazil'), ('ARGENTINA', 'Argentina'), ('CANADA', 'Canada'), ('MEXICO', 'Mexico'), ('GREAT BRITAIN', 'Great britain'), ('URUGUAY', 'Uruguay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=0, validators=[modules.core.utils.Validators.zero_not_first_integer]),
        ),
        migrations.AlterField(
            model_name='item',
            name='height_package_unit',
            field=models.IntegerField(default=0, validators=[modules.core.utils.Validators.zero_not_first_integer]),
        ),
        migrations.AlterField(
            model_name='item',
            name='length_package_unit',
            field=models.IntegerField(default=0, validators=[modules.core.utils.Validators.zero_not_first_integer]),
        ),
        migrations.AlterField(
            model_name='item',
            name='width_package_unit',
            field=models.IntegerField(default=0, validators=[modules.core.utils.Validators.zero_not_first_integer]),
        ),
    ]
