# Generated by Django 3.2.2 on 2023-01-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230111_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='working_hour_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='storage',
            name='working_hour_start',
            field=models.DateTimeField(default=None),
        ),
    ]
