# Generated by Django 3.2.2 on 2023-01-11 17:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230111_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(default=None, max_length=200, verbose_name=(('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'))),
        ),
    ]
