# Generated by Django 3.2.2 on 2023-01-11 17:49

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_storage_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='storage',
            name='drop_trailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='refrigerated_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storage',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default=None, max_length=27),
        ),
        migrations.AlterField(
            model_name='storage',
            name='working_hour_end',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='storage',
            name='working_hour_start',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='storage',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Contact', to='core.contact'),
        ),
    ]
