# Generated by Django 3.2.2 on 2023-01-19 13:57

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contact_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='observations',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='dispatch_contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='contact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Contact', to='core.contact'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.facility')),
                ('free_reschedule_enabled', models.BooleanField(default=True)),
                ('allow_repackaging_until_appointment', models.BooleanField(default=True)),
                ('time_allowed_for_repackaging_before_appointment', models.TimeField(blank=True, default=None, null=True)),
                ('detention_daily_cost', models.IntegerField(default=0)),
                ('dispatch_contact', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contact')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.facility',),
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hour_start', models.TimeField(default=None)),
                ('working_hour_end', models.TimeField(default=None)),
                ('working_days', multiselectfield.db.fields.MultiSelectField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default=None, max_length=27)),
                ('refrigerated_cargo', models.BooleanField(default=False)),
                ('drop_trailer', models.BooleanField(default=False)),
                ('drayage_enabled', models.BooleanField(default=False)),
                ('live_load', models.BooleanField(default=True)),
                ('hazmat', models.BooleanField(default=False)),
                ('dock_dispatch_contact', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contact')),
                ('warehouse', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Warehouse', to='core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateOffice',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.facility')),
                ('billable', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contact')),
            ],
            options={
                'verbose_name': 'Corporate Office',
                'verbose_name_plural': 'Corporate Offices',
            },
            bases=('core.facility',),
        ),
    ]
