# Generated by Django 3.2.2 on 2023-01-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230119_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='external_contact_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='internal_contact_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='yearly_revenue',
            field=models.IntegerField(default=0),
        ),
    ]
